name: ejercicio1-workflow
on:
  push:
    branches: [ master ]

jobs:
  Pruebas-de-SAST:
    runs-on: ubuntu-latest
    steps:
    - name: Pruebas de SAST
      run: echo 'Pruebas de SAST'

  Configurar-Archivo:
    runs-on: ubuntu-latest
    steps: 
    - name: Configurando archivo 
      run: echo -e "[Credentials]\nUSERNAME=${{ secrets.USERNAME }}\nPASSWORD=${{ secrets.PASSWORD }}" > credentials.ini
    - name: Creando archivo
      run: cat credentials.ini
    - name: Almacenar archivo credentials.ini
      uses: actions/upload-artifact@v3
      with:
        name: credentials
        path: credentials.ini

  Build-docker-image:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: docker build -t devops_ws . --tag devops_ws_$(date +%s)

